bump miniquad version
not-fl3/egui-miniquad pull request #18
Opened 2021-04-07 10:48 UTC by extrawurst

2021-04-07 13:39 UTC, emilk commented
Did you check if `doc/gl.js` also needs updating? (We should have some procedure for this, but we don't)

2021-04-07 14:51 UTC, extrawurst commented
ha good point, it does

2021-04-07 14:52 UTC, extrawurst commented
I was not aware that we copy over the `gl.js` from miniquad.

2021-04-07 14:58 UTC, extrawurst commented
`gl.js` updated

2021-04-07 15:02 UTC, not-fl3 commented
With not pinned miniquad version it is slightly easier to get a mismatched gl.js/miniquad version, I would consider keeping it pinned just in case

2021-04-07 18:17 UTC, emilk requested changes

2021-04-07 18:17 UTC, emilk commented on Cargo.toml
> +miniquad = { version = "0.3.0-alpha.29" }
```suggestion
miniquad = { version = "=0.3.0-alpha.29" }
```

we should pin while using pre-releases as they can contain breaking changes

2021-04-07 19:19 UTC, extrawurst commented
@not-fl3 speaking of **pre-releases** - is there any plan to release 0.3.0 ? :P

2021-04-07 20:43 UTC, emilk commented
Thanks!

2021-04-07 20:44 UTC, merged

2021-04-08 01:09 UTC, not-fl3 commented
> @not-fl3 speaking of **pre-releases** - is there any plan to release 0.3.0 ? :P

oh, that's a good question. 
Realistically speaking for the next few weeks I'll be too busy working on macroquad stable release and probably will just use alpha miniquad there :(